# -*- coding: utf-8 -*-
"""Studybuddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxjoMvQ4hlrq8eB5Z7Xxn9DBOkFJoV_R
"""

import streamlit as st
import requests
from bs4 import BeautifulSoup

st.set_page_config(page_title="MCQ to Notes", layout="wide")
st.title("🧠 MCQ to Detailed Notes Generator")

question = st.text_area("📌 Enter the MCQ Question:")
options = [st.text_input(f"Option {i+1}", key=f"opt{i}") for i in range(4)]
sources = st.text_input("🌐 Suggested sources (comma-separated URLs):")

def fetch_source_text(url):
    try:
        res = requests.get(url, timeout=5)
        soup = BeautifulSoup(res.text, 'html.parser')
        text = " ".join([p.get_text() for p in soup.find_all("p")])
        return text[:1000]
    except Exception as e:
        return ""

# Use a public API or forward request to Google Colab
def query_colab_llm(prompt):
    try:
        response = requests.post(
            "https://<your-colab-endpoint>.ngrok-free.app/predict",
            json={"prompt": prompt}
        )
        return response.json().get("response", "Error from Colab.")
    except Exception as e:
        return "Error connecting to LLM endpoint."

if st.button("🧠 Generate Notes"):
    source_texts = [fetch_source_text(url.strip()) for url in sources.split(",")]
    source_context = "\n\n".join(source_texts)

    full_prompt = f"""
You are a chemistry/biology expert.
Question: {question}
Options:
A. {options[0]}
B. {options[1]}
C. {options[2]}
D. {options[3]}

Analyze this MCQ:
1. Explain the concept in the question.
2. Justify each option.
3. If this involves a test, describe its discovery, reagents, interactions.
4. If it's about a reaction mechanism, explain each step.

Supplemental Source Text:
{source_context}
"""
    result = query_colab_llm(full_prompt)
    st.markdown("### 📝 Generated Notes")
    st.markdown(result)

